### ISSUE TITLE
Implement discovery execution policy

### ISSUE THREAD

**Issue by lubomirw** [CZERTAINLY/CZERTAINLY-IP-Discovery-Provider#32]
Discovery execution policy represents a way how the scanning should be performed to not create overhead on the network or similar issue.

There is configuration of execution that can be specified or calculated:
- batch size -  define how many IP addresses or hostnames will be scanned in one batch. The batch size will be calculated based on the number of IP addresses or hostnames to scan
- execution policy options:
  - sequential
  - parallel (how many parallel processes to create)
  - all at once

**Comment by 3keyroman** [comment]
Based on the description I would create a new attribute that would represent the number of concurrent processing of URLs and the default value will be 1, meaning that they are processed sequentially one by one, basically in one thread.

When there will be a higher number, discovery will open the number of separate threads to process the URLs. This will be done in parallel in this case.

I think all at once is unsafe, as we can have thousands of URLs, and in such case we will try to open many threads, probably crashing the system, if not properly handled. Or we can at least introduce maximum number of parallel executions.

What I think can be also beneficial is to configure time delay between the processing of URLs which can help to reduce complexity on the network avoiding blocking the connector on infrastructure level by IDS or IPS systems.

**Comment by semik** [comment]
Running thousands parallel connections might be challenge. 100 at once should be without problems handled by any system. Essential is to close connections properly, in C that means call close() to assure proper releasing of resources. 

Running it in strict sequence will lead into serious delays. By default Linux systems responds to unwanted connection request by sending RST packet. This is quite fast and allows quickly release needed resources. But many administrators do prefer to ignore unwanted incoming connection,  ie. set DROP rule in FW. This can lead into lengthy timeouts.  I would suggest to set default value for concurrent connections at least 10. This definitely should be configurable by the user, I expect on bigger networks admin will prefer to set higher value. 

In general scanning network is considered as an attack. However many admins of end-systems wont be able to differentiate scan from ordinary client connection. It is detectable on network level and might lead into blocking CZERTAINLY instance. Scan should be executed with proper permission, on both networks if they are not the same. 

I'm unsure about delay between tests, it will make tests even longer. And it makes no sense since CZERTAINLY is operated legally.

I think that occasional tests from our devel environment is bellow any threshold of possible IDS system. Any public IP is subject of periodical scans and tests for weak password at least several times per minute. More likely per second.

I think it would be helpful if CZERTAINLY can show progress and some ETA information about ongoing discovery. Depending on percentage sites ignoring probes runtime might wary a lot.
